#! /bin/bash

source /opt/ros/humble/setup.bash

# 自动获取脚本所在目录的父目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Source ROS2 环境
source /opt/ros/humble/setup.bash

cd "$PROJECT_ROOT/rmcs_ws"

colcon build --symlink-install 
